/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/sections/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/sections/AppHeader.vue')['default']
    AppRailNav: typeof import('./src/components/sections/AppRailNav.vue')['default']
    Authl: typeof import('./src/components/layouts/authl.vue')['default']
    Autonomy: typeof import('./src/components/pages-components/control-room/car-telemetry/Autonomy.vue')['default']
    Button: typeof import('./src/components/controls/Button.vue')['default']
    Card: typeof import('./src/components/containers/Card.vue')['default']
    CarProfileCard: typeof import('./src/components/pages-components/control-room/race-view/CarProfileCard.vue')['default']
    CarTelemetry: typeof import('./src/components/pages-components/control-room/CarTelemetry.vue')['default']
    CircularGauge: typeof import('./src/components/pages-components/carTracing/CircularGauge.vue')['default']
    copy: typeof import('./src/components/pages-components/SemiCircularGauge copy.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Leaderboard: typeof import('./src/components/pages-components/control-room/race-view/Leaderboard.vue')['default']
    LinearGauge: typeof import('./src/components/pages-components/LinearGauge.vue')['default']
    LinearGraph: typeof import('./src/components/pages-components/LinearGraph.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    Odometer: typeof import('./src/components/pages-components/control-room/car-telemetry/Odometer.vue')['default']
    OilTempGraph: typeof import('./src/components/pages-components/control-room/car-telemetry/OilTempGraph.vue')['default']
    RaceView: typeof import('./src/components/pages-components/control-room/race-view/RaceView.vue')['default']
    RightSidePanel: typeof import('./src/components/pages-components/control-room/race-view/RightSidePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SemiCircularGauge: typeof import('./src/components/pages-components/SemiCircularGauge.vue')['default']
    Sheet: typeof import('./src/components/containers/Sheet.vue')['default']
    Switch: typeof import('./src/components/controls/Switch.vue')['default']
    TeamComms: typeof import('./src/components/pages-components/control-room/TeamComms.vue')['default']
    Tires: typeof import('./src/components/pages-components/control-room/car-telemetry/Tires.vue')['default']
  }
}
