/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layouts/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layouts/AppHeader.vue')['default']
    Auth: typeof import('./src/components/views/Auth.vue')['default']
    Button: typeof import('./src/components/controls/Button.vue')['default']
    CarTracing: typeof import('./src/components/views/CarTracing.vue')['default']
    Events: typeof import('./src/components/views/Events.vue')['default']
    Footer: typeof import('./src/components/layouts/Footer.vue')['default']
    Header: typeof import('./src/components/layouts/AppHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    Race: typeof import('./src/components/views/Race.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signup: typeof import('./src/components/views/Signup.vue')['default']
    SystemManagement: typeof import('./src/components/views/SystemManagement.vue')['default']
  }
}
